/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.38.            *
*        Compiled Nov 24 2016, 13:25:31                              *
*                                                                    *
*        (c) 1998 - 2016 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: BlueBird                                              *
* Dimensions:  17 * 12                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmBlueBird;

static GUI_CONST_STORAGE unsigned long _acBlueBird[] = {
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00463752, 0x00463752, 0x00FBD055, 0x00FBD055, 0x00FBD055, 0x00463752, 0x00FAFAFA, 0x00FAFAFA, 0x00463752, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00463752, 0x00FBD055, 0x00FBD055, 0x00F8C14A, 0x00F8C14A, 0x00463752, 0x00FAFAFA, 0x00FAFAFA, 0x00FAFAFA, 0x00FAFAFA, 0x00463752, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF,
  0xFFFFFFFF, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0x00F8C14A, 0x00F8C14A, 0x00F8C14A, 0x00463752, 0x00CCE5D6, 0x00FAFAFA, 0x00FAFAFA, 0x00463752, 0x00FAFAFA, 0x00463752, 0xFFFFFFFF, 0xFFFFFFFF,
  0x00463752, 0x00FAFAFA, 0x00FAFAFA, 0x00FAFAFA, 0x00FAFAFA, 0x00463752, 0x00F8C14A, 0x00F8C14A, 0x00463752, 0x00CCE5D6, 0x00FAFAFA, 0x00FAFAFA, 0x00463752, 0x00FAFAFA, 0x00463752, 0xFFFFFFFF, 0xFFFFFFFF,
  0x00463752, 0x00FAFAFA, 0x00FAFAFA, 0x00FAFAFA, 0x00FAFAFA, 0x00FAFAFA, 0x00463752, 0x00F8C14A, 0x00F8C14A, 0x00463752, 0x00CCE5D6, 0x00FAFAFA, 0x00FAFAFA, 0x00FAFAFA, 0x00463752, 0xFFFFFFFF, 0xFFFFFFFF,
  0x00463752, 0x0083D8FC, 0x00FAFAFA, 0x00FAFAFA, 0x00FAFAFA, 0x0083D8FC, 0x00463752, 0x00F8C14A, 0x00F8C14A, 0x00F8C14A, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0xFFFFFFFF,
  0xFFFFFFFF, 0x00463752, 0x0083D8FC, 0x0083D8FC, 0x0083D8FC, 0x00463752, 0x00F8C14A, 0x00F8C14A, 0x00F8C14A, 0x00463752, 0x002E60E4, 0x002E60E4, 0x002E60E4, 0x002E60E4, 0x002E60E4, 0x002E60E4, 0x00463752,
  0xFFFFFFFF, 0xFFFFFFFF, 0x00463752, 0x00463752, 0x00463752, 0x00D1A341, 0x00D1A341, 0x00D1A341, 0x00463752, 0x002E60E4, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0xFFFFFFFF,
  0xFFFFFFFF, 0xFFFFFFFF, 0x00463752, 0x00D1A341, 0x00D1A341, 0x00D1A341, 0x00D1A341, 0x00D1A341, 0x00D1A341, 0x00463752, 0x002E60E4, 0x002E60E4, 0x002E60E4, 0x002E60E4, 0x002E60E4, 0x00463752, 0xFFFFFFFF,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00463752, 0x00463752, 0x00D1A341, 0x00D1A341, 0x00D1A341, 0x00D1A341, 0x00D1A341, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0xFFFFFFFF, 0xFFFFFFFF,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0x00463752, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF
};

GUI_CONST_STORAGE GUI_BITMAP bmBlueBird = {
  17, // xSize
  12, // ySize
  68, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)_acBlueBird,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
